extends SceneTree
const Catalog := preload("res://scripts/resource_catalog.gd")
const World := preload("res://scripts/simulation_world.gd")
const Controller := preload("res://scripts/game_controller.gd")
const Commands := preload("res://scripts/commands.gd")
const Context := preload("res://scripts/context_resolver.gd")
const Orders := preload("res://scripts/order_pipeline.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var catalog = Catalog.new()
	catalog.load()
	construction_handoff(catalog)
	adjacent_farms(catalog)
	manual_and_automatic_deposit(catalog)
	tree_lifecycle(catalog)
	for failure in failures: push_error(failure)
	print("Worker construction, farming, deposit and tree regressions: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func configured(catalog):
	var world = World.new(Vector2i(48, 48))
	world.navigation_grid.configure_terrain(func(_cell): return "grass")
	world.set_gamespec(catalog.gamespec_data)
	world.set_object_catalog(catalog.object_catalog_data)
	world.set_graphics_catalog(catalog.graphics_catalog_data)
	world.set_runtime_catalog(catalog.runtime_catalog_data)
	world.set_team_civilization(1, 13)
	world.set_team_civilization(2, 13)
	for resource in range(4): world.set_resource_amount(1, resource, 10000)
	world.add_building(900, "town_center", Vector2(8, 8), 1)
	var enemy: Dictionary = world.add_unit(2, "clubman", Vector2(44, 44), false)
	enemy["stance"] = "passive"
	return world
func construction_handoff(catalog) -> void:
	var world = configured(catalog)
	var first: Dictionary = world.add_unit(1, "villager", Vector2(15, 14), false)
	var second: Dictionary = world.add_unit(1, "villager", Vector2(17, 14), false)
	var foundation: Variant = world.assign_command_build([first], "house", Vector2(16, 17))
	check(foundation != null, "first worker places foundation")
	if foundation == null: return
	var controller = Controller.new(world)
	for tick in range(35): controller.advance_frame(0.05, 1, 2)
	check(float(foundation["construction_progress"]) > 0, "first worker starts actual construction")
	world.halt_unit(first, "abandon")
	check(foundation["builders"].is_empty(), "abandoning releases actual builder as well as approach slot")
	var wood_before: int = world.get_resource_amount(1, 1)
	var target: Dictionary = foundation.duplicate(true)
	target["entity_type"] = "foundation"
	var resolved := Context.resolve([second], target, Vector2.ZERO, 1)
	check(resolved.get("building_type") == "house", "right click resolves foundation's canonical kind")
	var command = Commands.BuildCommand.new(controller.tick_index, [int(second["id"])], String(resolved.get("building_type", "")), resolved.get("target", Vector2.ZERO))
	controller.enqueue_command(command, true, 1)
	controller.process_commands()
	check(controller.get_command_result(command.sequence_id).get("accepted", false), "replacement worker accepts context build command")
	check(world.get_resource_amount(1, 1) == wood_before, "resuming existing foundation does not charge twice")
	for tick in range(800):
		controller.advance_frame(0.05, 1, 2)
		if foundation["state"] == "complete": break
	check(foundation["state"] == "complete", "replacement worker completes abandoned building")
func adjacent_farms(catalog) -> void:
	var world = configured(catalog)
	world.grant_technology(1, 101)
	world.add_building(901, "market", Vector2(6, 16), 1)
	world.add_unit(1, "villager", Vector2(17, 14), false)
	world.add_unit(1, "villager", Vector2(22, 14), false)
	var first: Variant = world.place_foundation(1, "farm", Vector2(18, 17))
	check(first != null, "farm fixture is placeable")
	if first == null: return
	check(world.can_place_foundation(1, "farm", Vector2(21, 17)), "native three-cell farms may share an edge")
	check(world.can_place_foundation(1, "farm", Vector2(18, 20)), "farm adjacency works on both axes")
	check(not world.can_place_foundation(1, "farm", Vector2(20, 17)), "overlapping farm tiles remain rejected")
	var second: Variant = world.place_foundation(1, "farm", Vector2(21, 17))
	check(second != null, "adjacent foundations can be placed, not only previewed")
	if second == null: return
	world.complete_foundation(first)
	world.complete_foundation(second)
	check(world.navigation_grid.is_walkable(Vector2i(18, 17)) and world.navigation_grid.is_walkable(Vector2i(21, 17)), "both farm interiors stay traversable")
func manual_and_automatic_deposit(catalog) -> void:
	var world = configured(catalog)
	var worker: Dictionary = world.add_unit(1, "villager", Vector2(12, 11), false)
	var berries: Dictionary = world.add_resource("berries", Vector2(14.5, 11.5), 100)
	world.assign_command_gather([worker], int(berries["id"]))
	for step in range(5): world.gather(int(berries["id"]), worker)
	check(world.assign_command_return_resources([worker], 900), "manual deposit is accepted")
	worker["pos"] = worker["dropoff_position"]
	var before: int = world.get_food()
	world.gathering_system.update_dropoff_order(worker, 0.05)
	check(world.get_food() == before + 5, "manual deposit returns exact cargo")
	check(worker["task"] == "idle" and worker["resource_id"] == -1, "manual deposit stops instead of resuming old gathering")
	world.assign_command_gather([worker], int(berries["id"]))
	for step in range(5): world.gather(int(berries["id"]), worker)
	var probe = preload("res://scripts/performance_probe.gd").new()
	world.pathfinder.set_performance_probe(probe)
	check(world.begin_resource_return(worker), "automatic return is available")
	check(int(probe.counters.get("navigation.path_queries", 0)) == 0, "automatic deposit at the current slot performs no redundant route search")
	check(worker["diagnostic_reason"] != "no_path", "an already reached deposit slot never becomes an unreachable order")
	worker["pos"] = worker["dropoff_position"]
	world.gathering_system.update_dropoff_order(worker, 0.05)
	check(worker["task"] == "gather" and worker["resource_id"] == berries["id"], "automatic deposit continues normal gathering")
	# Explicit queued commands still run after the manual deposit ends.
	world.gather(int(berries["id"]), worker)
	check(world.assign_command_return_resources([worker], 900), "second manual deposit accepted")
	Orders.append_queued(worker, {"type": "move", "target_position": Vector2(20, 20)})
	worker["pos"] = worker["dropoff_position"]
	world.gathering_system.update_dropoff_order(worker, 0.05)
	check(Orders.queued(worker).size() == 1, "manual deposit preserves explicitly queued next orders")
func tree_lifecycle(catalog) -> void:
	var world = configured(catalog)
	var worker: Dictionary = world.add_unit(1, "villager", Vector2(16, 15), false)
	var tree: Dictionary = world.add_resource("tree", Vector2(18.5, 15.5), 3)
	var projection: Dictionary = world.compact_render_projection(tree)
	check(projection.get("tree_phase") == "standing", "retained render projection starts with standing tree")
	world.assign_command_gather([worker], int(tree["id"]))
	world.gather(int(tree["id"]), worker)
	check(tree["hp"] < tree["max_hp"] and tree["hp"] > 0, "initial chop damages original tree HP")
	projection = world.compact_render_projection(tree)
	check(projection.get("tree_phase") == "chopping" and projection.get("hp") == tree["hp"], "cached tree exposes damage while chopping")
	check(tree["amount"] == 3 and worker["carried_amount"] == 0, "standing tree yields no wood before felling")
	for step in range(100):
		if tree["tree_phase"] == "falling": break
		world.gather(int(tree["id"]), worker)
	check(tree["tree_phase"] == "falling" and tree["hp"] == 0, "tree enters falling phase after all HP is removed")
	check(world.falling_resource_nodes.size() == 1, "only active falling tree is scheduled")
	world.gather(int(tree["id"]), worker)
	check(tree["amount"] == 3, "falling tree cannot be harvested before landing")
	world.advance_resource_lifecycle(0.25)
	check(tree["tree_phase"] == "falling", "fall is visible for a finite animation interval")
	projection = world.compact_render_projection(tree)
	check(projection.get("tree_phase") == "falling" and projection.get("tree_fall_elapsed") == 0.25, "cached projection advances visible fall animation")
	world.advance_resource_lifecycle(0.5)
	check(tree["tree_phase"] == "felled" and world.falling_resource_nodes.is_empty(), "landed tree leaves active lifecycle list")
	projection = world.compact_render_projection(tree)
	check(projection.get("tree_phase") == "felled", "cached projection changes to landed trunk")
	check(catalog.resource_frame_info(projection).get("asset_name") == "graphic_636", "retained renderer receives original felled branches asset")
	check(not catalog.resource_frame_info(tree).is_empty(), "felled trunk uses original branches graphic")
	for step in range(3): world.gather(int(tree["id"]), worker)
	check(worker["carried_amount"] == 3 and tree["tree_phase"] == "stump", "fallen wood depletes to a persistent stump")
	check(world.navigation_grid.is_walkable(Vector2i(tree["pos"])), "empty stump releases pathfinding footprint")
	projection = world.compact_render_projection(tree)
	check(projection.get("tree_phase") == "stump", "cached projection updates after wood depletion")
	check(catalog.resource_frame_info(tree).get("asset_name") == "tree_stump", "empty tree displays original stump")
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
