extends SceneTree
const Catalog := preload("res://scripts/resource_catalog.gd")
const World := preload("res://scripts/simulation_world.gd")
const Snapshot := preload("res://scripts/simulation_snapshot.gd")
const ViewModel := preload("res://scripts/hud_view_model.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var catalog = Catalog.new()
	catalog.load()
	var world = World.new(Vector2i(36, 36))
	world.set_gamespec(catalog.gamespec_data)
	world.set_object_catalog(catalog.object_catalog_data)
	world.set_graphics_catalog(catalog.graphics_catalog_data)
	world.set_runtime_catalog(catalog.runtime_catalog_data)
	world.navigation_grid.configure_terrain(func(_cell): return "grass")
	world.set_team_civilization(1, 13)
	world.set_team_civilization(2, 13)
	world.add_building(900, "town_center", Vector2(10, 10), 1)
	var animal: Dictionary = world.add_unit(0, "gazelle", Vector2(11, 12), false)
	var enemy: Dictionary = world.add_unit(2, "clubman", Vector2(12, 12), false)
	var enemy_building: Dictionary = world.add_building(901, "barracks", Vector2(14, 10), 2)
	world.set_resource_amount(2, 0, 1000)
	world.enqueue_unit_production(901, 2, "clubman")
	world.update_fog_of_war()
	var model = ViewModel.new()
	model.configure(catalog.runtime_catalog_data, catalog.localization, catalog.object_catalog_data)
	for entity in [animal, enemy, enemy_building]:
		var entity_id := int(entity["id"])
		for compact in [false, true]:
			var snapshot := Snapshot.with_queries(world, 1, 1, {"compact_render_entities": compact, "always_include_entity_ids": [entity_id]})
			var hud: Dictionary = model.build(snapshot, [entity_id] as Array[int], "RECTANGLE")
			check(hud["selection"]["count"] == 1, "visible foreign object is inspectable")
			check(hud["selection"]["leader"].get("hp") == roundi(entity["hp"]), "inspection shows real observed HP")
			check(hud["selection"]["leader"].get("icon_id", -1) >= 0, "inspection resolves portrait icon")
			check(hud["read_only"] and hud["commands"].is_empty() and hud["queue"].is_empty(), "foreign inspection has no orders, production or research")
			for building in snapshot["buildings"]:
				if building["id"] == 901: check(not building.has("production_queue") and not building.has("command_options"), "snapshot does not disclose enemy production")
	var own: Dictionary = world.add_unit(1, "villager", Vector2(10, 12), false)
	var own_model: Dictionary = model.build(Snapshot.with_queries(world, 2, 1), [int(own["id"])] as Array[int], "RECTANGLE")
	check(not own_model["read_only"] and not own_model["commands"].is_empty(), "own worker retains command UI")
	# Main scene selection uses the same real click/picking path as the game.
	var viewport := SubViewport.new()
	viewport.size = Vector2i(1280, 720)
	root.add_child(viewport)
	var game = load("res://main.tscn").instantiate()
	viewport.add_child(game)
	await process_frame
	game.game_controller.set_paused(true)
	var visible_position := Vector2(game.simulation_world.get_units()[0]["pos"]) + Vector2(0, 2)
	var observed: Dictionary = game.simulation_world.add_unit(0, "gazelle", visible_position, false)
	game.sync_world_state()
	var point: Vector2 = game.world_to_screen(visible_position)
	game.finish_selection(point, point)
	check(game.player_control_state.is_selected(int(observed["id"])), "click selects a neutral animal through real picking")
	game.sync_world_state()
	check(game.player_control_state.is_selected(int(observed["id"])), "snapshot refresh does not prune visible neutral selection")
	check(game.selected_units().is_empty(), "inspection never makes neutral animal controllable")
	check(game.hud_model["selection"]["leader"].get("kind") == "gazelle", "left HUD shows clicked animal")
	viewport.free()
	for failure in failures: push_error(failure)
	print("Foreign unit and animal inspection/privacy: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
