extends SceneTree
const World := preload("res://scripts/simulation_world.gd")
const Controller := preload("res://scripts/game_controller.gd")
const Commands := preload("res://scripts/commands.gd")
const Dependency := preload("res://scripts/cache_dependency.gd")
const Journal := preload("res://scripts/entity_change_journal.gd")
const Contract := preload("res://scripts/entity_read_contract.gd")
const Checkpoint := preload("res://scripts/game_checkpoint.gd")
const Replay := preload("res://scripts/replay_system.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var world := World.new(Vector2i(32, 32))
	world.reset_game(false)
	world.navigation_grid.configure_terrain(func(_cell): return "land")
	var unit: Dictionary = world.add_unit(1, "clubman", Vector2(4.5, 4.5), false)
	world.add_unit(2, "clubman", Vector2(28.5, 28.5), false)
	world.entity_changes.flush()
	check(world.entity_changes.revision_for(int(unit["id"])) > 0, "ordinary worlds publish source notifications from creation")
	var controller := Controller.new(world)
	controller.set_speed_multiplier(1.0)
	world.set_entity_change_comparison(true)
	var cursor := Dependency.stamp(world, Dependency.ENTITIES)
	world.set_entity_field(unit, "pos", unit["pos"])
	check(Dependency.changes(world, Dependency.ENTITIES, cursor)["ids"].is_empty(), "unchanged assignment publishes nothing")
	var old := Contract.render(unit)
	var original_position: Vector2 = unit["pos"]
	controller.enqueue_command(Commands.MoveCommand.new(1, [int(unit["id"])], Vector2(8.5, 4.5)), true, 1)
	for step in range(15): controller.advance_frame(0.05, 1, 2)
	var delta := Dependency.changes(world, Dependency.ENTITIES, cursor)
	check(delta["ids"].has(int(unit["id"])) and int(delta["masks"][int(unit["id"])]) & Journal.POSITION, "real command movement updates the changed unit")
	check(old["pos"] == original_position, "retained render snapshot stays unchanged")
	cursor = delta["stamp"]
	world.begin_entity_order(unit, "move", -1, Vector2(10.5, 4.5))
	delta = Dependency.changes(world, Dependency.ENTITIES, cursor)
	check((int(delta["masks"].get(int(unit["id"]), 0)) & Journal.ACTIVITY) != 0, "a repeated task with a new order invalidates activity")
	world.halt_unit(unit)
	controller.advance_frame(0.05, 1, 2)
	check(String(unit["task"]) == "idle", "stop preserves the command lifecycle")
	world.set_entity_field(unit, "hp", float(unit["hp"]) - 1.0)
	world.transfer_entity_ownership(unit, 2)
	controller.advance_frame(0.05, 1, 2)
	cursor = Dependency.stamp(world, Dependency.ENTITIES)
	var foundation: Dictionary = world.add_building(1001, "house", Vector2(16.5, 16.5), 2, false)
	var old_foundation := Contract.render(foundation)
	cursor = Dependency.stamp(world, Dependency.ENTITIES)
	check(world.cancel_foundation(1001), "the real foundation cancellation succeeds")
	var cancelled := Dependency.changes(world, Dependency.ENTITIES, cursor)
	check(world.find_building(1001) == null and cancelled["removed_ids"].has(1001), "cancellation publishes the physically removed building")
	check(not world.entity_changes.versions_by_id.has(1001), "cancellation releases the live version record")
	check(old_foundation["id"] == 1001 and old_foundation["pos"] == Vector2(16.5, 16.5), "cancelled building publication remains immutable")
	cursor = Dependency.stamp(world, Dependency.ENTITIES)
	var replay := Replay.new()
	var state_hash := replay.world_state_hash(world, controller.tick_index, controller)
	world.entity_changes.mark(int(unit["id"]), Journal.ALL)
	world.entity_changes.flush()
	check(replay.world_state_hash(world, controller.tick_index, controller) == state_hash, "journal and versions stay outside canonical state")
	var data := Checkpoint.capture(world, controller, {}, {"size": world.map_size})
	check(Checkpoint.restore(data, world, controller), "checkpoint restores into the same owner")
	check(Dependency.changes(world, Dependency.ENTITIES, cursor)["full"], "restore rejects old epoch cursors even when IDs repeat")
	check(world.entity_changes.revision_for(int(unit["id"])) > 0, "restore reconstructs derived versions")
	check(replay.world_state_hash(world, controller.tick_index, controller) == state_hash, "checkpoint reconstruction preserves authoritative state")
	# The checkpoint replaced dictionaries; use the current authoritative row.
	unit = world.find_unit(int(unit["id"]))
	world.set_entity_field(unit, "hp", 0.0)
	world.begin_death(unit)
	controller.advance_frame(0.05, 1, 2)
	unit["removed"] = true
	world.unit_removal_pending = true
	cursor = Dependency.stamp(world, Dependency.ENTITIES)
	world.purge_removed_units()
	check(Dependency.changes(world, Dependency.ENTITIES, cursor)["removed_ids"].has(int(unit["id"])), "physical removal publishes a tombstone")
	world.reset_game(false)
	check(world.entity_changes.versions_by_id.is_empty() and world.entity_changes.history.is_empty(), "new match releases all journal state")
	unit = world.add_unit(1, "clubman", Vector2(5.5, 5.5), false)
	world.set_entity_field(unit, "hp", 7)
	cursor = Dependency.stamp(world, Dependency.ENTITIES)
	check(typeof(unit["hp"]) == TYPE_INT and world.entity_changes.revision_for(int(unit["id"])) > 0, "mandatory tracking preserves exact assignment types")
	world.set_entity_field(unit, "pos", Vector2(6.5, 5.5))
	check(Dependency.changes(world, Dependency.ENTITIES, cursor)["ids"].has(int(unit["id"])), "subscribed writes continue publishing deltas")
	world.set_entity_change_comparison(false)
	check(not world.entity_changes.comparison_enabled and not world.entity_changes.versions_by_id.is_empty(), "diagnostic comparison does not disable production notifications")
	world.reset_game(false)
	check(Dependency.changes(world, Dependency.ENTITIES, cursor)["full"], "new worlds reject cursors from the old epoch")
	for failure in failures: push_error(failure)
	print("Entity change ownership: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
