extends SceneTree
const World := preload("res://scripts/simulation_world.gd")
const Store := preload("res://scripts/ai_observation_store.gd")
const Preparation := preload("res://scripts/ai_observation_preparation.gd")
const Ai := preload("res://scripts/ai_player.gd")
const Task := preload("res://scripts/ai_planning_task.gd")
const Queue := preload("res://scripts/ai_decision_queue.gd")
const Coordinator := preload("res://scripts/isolated_task_coordinator.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var world := World.new(Vector2i(24, 24))
	world.navigation_grid.configure_terrain(func(_cell): return "grass")
	world.add_unit(1, "villager", Vector2(8, 8), false)
	var store := Store.new()
	var preparation := Preparation.new()
	var ai := Ai.new({"team": 1, "ai": {"enabled": true}})
	var first: Dictionary = preparation.capture(world, store, ai, 0, 8)
	check(not first.is_empty() and not first.get("pending", false), "short stages finish without holding another frame")
	check(world.read_generation_pins == 0 and preparation.captures.is_empty(), "completed capture releases its generation")
	var second: Dictionary = preparation.capture(world, store, ai, 0, 8)
	check(not second.get("pending", false), "warm capture has no mandatory frame gaps")
	check(int(second.get("tick", -1)) == 8 and int(second.get("snapshot", {}).get("tick", -1)) == 0, "source and predetermined apply tick stay distinct")
	check(Task.run(first) == Task.run(second), "coalescing stages preserves planner commands and state")
	var coordinator := Coordinator.new()
	var queue := Queue.new()
	queue.begin([ai], 0, 8, func(player, target): return preparation.capture(world, store, player, 0, target))
	var status: Dictionary = queue.poll(coordinator, 0, 1)
	check(queue.is_prepared() and bool(queue.gate(status, 1)["ready"]), "simulation can advance as soon as the short capture is detached")
	check(not bool(queue.gate(status, 8)["ready"]), "worker proposals remain gated at their deadline")
	queue.cancel(coordinator)
	coordinator.shutdown()
	for _actor in range(96): world.add_unit(1, "villager", Vector2(9, 9), false)
	var pending: Dictionary = preparation.capture(world, store, ai, 0, 8)
	check(bool(pending.get("pending", false)), "actor overflow still yields at its record quota")
	check(int(preparation.captures[1]["projection"]["cursor"]) == Preparation.ACTORS_PER_PORTION and world.read_generation_pins == 1, "yielded observation retains its exact source and bounded cursor")
	preparation.clear()
	check(world.read_generation_pins == 0, "cancel releases an unfinished capture")
	world.shutdown_derived_state()
	var cold := World.new(Vector2i(64, 64))
	cold.navigation_grid.configure_terrain(func(_cell): return "grass")
	cold.add_unit(1, "villager", Vector2(8, 8), false)
	store.clear()
	pending = preparation.capture(cold, store, ai, 0, 8)
	check(bool(pending.get("pending", false)) and preparation.captures[1]["phase"] == "navigation", "cold navigation still yields at its cell quota")
	check(cold.ai_navigation_knowledge.last_prepared_cells == cold.ai_navigation_knowledge.DEFAULT_PREPARE_CELLS, "coalescing never increases the navigation slice")
	preparation.clear()
	cold.shutdown_derived_state()
	for failure in failures: push_error(failure)
	print("AI capture frame cadence: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
