extends SceneTree
const World := preload("res://scripts/simulation_world.gd")
const Store := preload("res://scripts/ai_observation_store.gd")
const Preparation := preload("res://scripts/ai_observation_preparation.gd")
const Ai := preload("res://scripts/ai_player.gd")
const Queue := preload("res://scripts/ai_decision_queue.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var world := World.new(Vector2i(24, 24))
	world.navigation_grid.configure_terrain(func(_cell): return "grass")
	var unit: Dictionary = world.add_unit(1, "villager", Vector2(8, 8), false)
	world.entity_changes.flush()
	check(world.entity_changes.revision_for(int(unit["id"])) > 0, "source notifications are mandatory from creation")
	# Exceed the actor quota so cancellation/save-resume exercises actual
	# unfinished work instead of relying on a mandatory phase/frame gap.
	for _actor in range(96): world.add_unit(1, "villager", Vector2(9, 9), false)
	var store := Store.new()
	var preparation := Preparation.new()
	var ai := Ai.new({"team": 1, "ai": {"enabled": true}})
	var capture := func(player, target): return preparation.capture(world, store, player, 0, target)
	var queue := Queue.new()
	queue.begin([ai], 0, 8, capture)
	var pending: Dictionary = capture.call(ai, 8)
	check(bool(pending.get("pending", false)) and world.read_generation_pins == 1, "partial capture pins a fixed source generation")
	var serialized := queue.canonical_state()
	var restored := Queue.new()
	check(restored.restore_state(serialized, [ai], 0, capture), "an uncaptured decision resumes from the same source boundary")
	preparation.clear()
	check(world.read_generation_pins == 0 and preparation.captures.is_empty(), "cancellation releases all pinned generation data")
	var animation_revision := world.entity_changes.revision_for(int(unit["id"]), 32)
	world.advance_entity_animation(unit, "Move", 0.05)
	world.entity_changes.flush()
	check(world.entity_changes.revision_for(int(unit["id"]), 32) > animation_revision, "animation state transitions notify the appearance owner")
	world.set_entity_field(unit, "target", Vector2(12, 8))
	world.set_entity_field(unit, "task", "move")
	world.unit_activity_registry.synchronize(world)
	check(world.unit_activity_registry.is_active(int(unit["id"])), "a source command wakes an idle actor")
	world.set_entity_field(unit, "pos", Vector2(12, 8))
	world.set_entity_field(unit, "previous_pos", Vector2(12, 8))
	world.set_entity_field(unit, "target", Vector2(12, 8))
	world.set_entity_field(unit, "task", "idle")
	world.set_entity_field(unit, "path", [])
	world.set_entity_field(unit, "path_index", 0)
	world.set_entity_field(unit, "actual_velocity", Vector2.ZERO)
	world.unit_activity_registry.synchronize(world)
	check(not world.unit_activity_registry.is_active(int(unit["id"])), "completion retires an actor through source events")
	world.shutdown_derived_state()
	for failure in failures: push_error(failure)
	print("Incremental runtime generation: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
