extends SceneTree
const World := preload("res://scripts/simulation_world.gd")
const Knowledge := preload("res://scripts/ai_navigation_knowledge.gd")
const Probe := preload("res://scripts/performance_probe.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var kernel = ClassDB.instantiate("RoRPathKernel")
	var mask := PackedByteArray()
	mask.resize(64); mask.fill(1)
	kernel.configure(8, 8, 1, mask)
	var version: int = kernel.get_walkability_version()
	kernel.update_walkable(2, PackedInt32Array([4]), PackedByteArray([1]))
	check(kernel.get_walkability_version() == version, "unchanged access preserves dependency version")
	kernel.update_walkable(3, PackedInt32Array([4]), PackedByteArray([0]))
	check(kernel.get_walkability_version() > version, "actual obstruction advances dependency version")
	var world := World.new(Vector2i(32, 32))
	world.navigation_grid.configure_terrain(func(_cell): return "grass")
	var unit: Dictionary = world.add_unit(1, "villager", Vector2(6.5, 6.5), false)
	unit["diagnostic_reason"] = "no_group_route"
	var other: Dictionary = world.add_unit(2, "villager", Vector2(24.5, 24.5), false)
	var fog = world.get_fog_of_war()
	for y in range(32):
		for x in range(32): fog.reveal_explored_cell(1, Vector2i(x, y))
	var probe := Probe.new()
	world.set_performance_probe(probe)
	var knowledge := Knowledge.new()
	var old: Dictionary = knowledge.snapshot(world, fog, 1)
	var preserved := old.duplicate(true)
	compare(world, knowledge, "initial recovery")
	var reused := int(probe.counters.get("ai.navigation.recovery_reused", 0))
	other["pos"] += Vector2(1, 0)
	world.rebuild_spatial_index(false)
	world.update_fog_of_war()
	compare(world, knowledge, "hidden remote motion")
	check(int(probe.counters.get("ai.navigation.recovery_reused", 0)) > reused, "hidden remote motion reuses lawful recovery")
	other["pos"] = Vector2(7.5, 6.5)
	world.rebuild_spatial_index(false)
	world.update_fog_of_war()
	compare(world, knowledge, "visible neighbor arrival")
	other["hp"] = 0.0
	compare(world, knowledge, "visible neighbor death")
	unit["footprint_radius"] = 0.65
	compare(world, knowledge, "footprint technology change")
	world.navigation_grid.occupy([Vector2i(7, 7)], "obstacle", 900)
	compare(world, knowledge, "new local obstruction")
	world.navigation_grid.release_occupant([Vector2i(7, 7)], "obstacle", 900)
	compare(world, knowledge, "obstruction removed")
	check(old == preserved, "old navigation publications remain immutable")
	var entry: Dictionary = knowledge.entries[1]
	for i in range(Knowledge.MAX_RECOVERY_CACHE_ENTRIES + 32): knowledge._remember_recovery(entry, 10000 + i, [i], null)
	check(entry["recovery_cache"].size() <= Knowledge.MAX_RECOVERY_CACHE_ENTRIES, "record cap evicts old recovery entries")
	check(entry["recovery_cache_bytes"] <= Knowledge.MAX_RECOVERY_CACHE_BYTES, "logical payload stays bounded")
	var huge := PackedByteArray()
	huge.resize(Knowledge.MAX_RECOVERY_CACHE_BYTES + 1)
	knowledge._remember_recovery(entry, 99999, [huge], null)
	check(not entry["recovery_cache"].has(99999), "oversized dependency remains uncached")
	unit["diagnostic_reason"] = ""
	knowledge.snapshot(world, fog, 1)
	check(entry["recovery_cache"].is_empty(), "inactive and removed candidates release recovery entries")
	knowledge.clear()
	check(knowledge.entries.is_empty(), "new world clears all dependency generations")
	world.task_coordinator.shutdown()
	for failure in failures: push_error(failure)
	print("Lawful recovery cache checks: ", failures.size(), " failures")
	quit(0 if failures.is_empty() else 1)
func compare(world, knowledge, label: String) -> void:
	var reference := Knowledge.new()
	reference.recovery_cache_enabled = false
	check(knowledge.snapshot(world, world.get_fog_of_war(), 1) == reference.snapshot(world, world.get_fog_of_war(), 1), label + " matches uncached query")
func check(condition: bool, message: String) -> void:
	if not condition: failures.append(message)
