extends SceneTree
const World := preload("res://scripts/simulation_world.gd")
const Catalog := preload("res://scripts/resource_catalog.gd")
const Probe := preload("res://scripts/performance_probe.gd")
var failures: Array[String] = []
func _initialize() -> void:
	var catalog := Catalog.new()
	catalog.load_generated_data()
	var world := World.new(Vector2i(32, 32))
	world.set_gamespec(catalog.gamespec_data)
	world.set_object_catalog(catalog.object_catalog_data)
	world.set_graphics_catalog(catalog.graphics_catalog_data)
	world.set_runtime_catalog(catalog.runtime_catalog_data)
	world.navigation_grid.configure_terrain(func(_cell): return "grass")
	world.set_resource_amount(1, 0, 2000)
	world.set_resource_amount(1, 1, 2000)
	var barracks: Dictionary = world.add_building(701, "barracks", Vector2(8.5, 8.5), 1)
	var tc: Dictionary = world.add_building(702, "town_center", Vector2(15.5, 15.5), 1)
	var system = world.production_system
	var probe := Probe.new()
	world.set_performance_probe(probe)
	check_reference(world, barracks)
	var initial := world.get_unit_production_availability(701, 1, "clubman")
	world.set_resource_amount(1, 0, 0)
	check_reference(world, barracks)
	check(not world.get_unit_production_availability(701, 1, "clubman")["accepted"], "affordability changes without rebuilding rare rules")
	world.set_resource_amount(1, 0, 2000)
	check(world.get_unit_production_availability(701, 1, "clubman") == initial, "resources restore availability and old result remains detached")
	barracks["production_queue"].resize(15)
	check_reference(world, barracks)
	check(world.get_unit_production_availability(701, 1, "clubman")["reason"] == "queue_full", "queue capacity is never cached")
	barracks["production_queue"].clear()
	world.set_entity_field(barracks, "hp", 0.0)
	check_reference(world, barracks)
	check(world.get_unit_production_availability(701, 1, "clubman")["reason"] == "invalid_production_building", "destroyed producer is validated live")
	world.set_entity_field(barracks, "hp", barracks["max_hp"])
	world.technology_system.disable_scenario_object(1, 73)
	check_reference(world, barracks)
	check(world.get_unit_production_availability(701, 1, "clubman")["reason"] == "unit_unavailable", "technology revision invalidates rare eligibility")
	check_reference(world, tc)
	check(int(probe.counters.get("ai.commands.rare_templates_reused", 0)) > 0, "stable conditions reuse prepared templates")
	for index in range(system.MAX_OPTION_TEMPLATE_CACHE_ENTRIES + 2):
		system._remember_option_template("overflow:" + str(index), {"test": index})
	check(system.option_template_cache.size() <= system.MAX_OPTION_TEMPLATE_CACHE_ENTRIES and system.option_template_cache_bytes <= system.MAX_OPTION_TEMPLATE_CACHE_BYTES, "rare template cache has entry and logical byte limits")
	var huge := {"text": "x".repeat(system.MAX_OPTION_TEMPLATE_CACHE_BYTES + 1)}
	system._remember_option_template("oversized", huge)
	check(not system.option_template_cache.has("oversized"), "oversized facts use the uncached reference path")
	world.reset_game(false)
	check(system.option_template_cache.is_empty(), "new game releases rare templates")
	for failure in failures: push_error(failure)
	print("AI preparation templates: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func check_reference(world, building: Dictionary) -> void:
	world.production_system.option_template_cache_enabled = false
	var expected_units: Array = world.get_unit_production_options(int(building["id"]), 1)
	var expected_research: Array = world.get_research_options(int(building["id"]), 1)
	var expected: Dictionary = world.get_unit_production_availability(int(building["id"]), 1, "clubman")
	world.production_system.option_template_cache_enabled = true
	check(world.get_unit_production_options(int(building["id"]), 1) == expected_units, "cached unit options equal the live reference")
	check(world.get_research_options(int(building["id"]), 1) == expected_research, "cached research options equal the live reference")
	check(world.get_unit_production_availability(int(building["id"]), 1, "clubman") == expected, "single availability preserves rejection precedence")
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
