extends SceneTree
const Grid := preload("res://scripts/navigation_grid.gd")
const Finder := preload("res://scripts/pathfinder.gd")
const Probe := preload("res://scripts/performance_probe.gd")
var failures: Array[String] = []
func _initialize() -> void:
	for native in [false, true]:
		var grid = Grid.new(Vector2i(40, 40))
		grid.configure_terrain(func(_cell): return "grass")
		var finder = Finder.new(grid)
		finder.set_native_enabled(native)
		var probe := Probe.new()
		finder.set_performance_probe(probe)
		var original: Array = finder.find_path(Vector2(2.5, 3.5), Vector2(15.5, 3.5))
		grid.occupy([Vector2i(35, 35)], "building", 1)
		check(finder.find_path(Vector2(2.5, 3.5), Vector2(15.5, 3.5)) == original and finder.cache_hits == 1, "unrelated edits preserve valid geometry")
		grid.occupy([Vector2i(8, 3)], "building", 2)
		var changed: Array = finder.find_path(Vector2(2.5, 3.5), Vector2(15.5, 3.5))
		check(changed != original and changed.size() > 1, "route obstruction invalidates affected geometry")
		var raw: Array = finder.find_cell_path(Vector2i(2, 3), Vector2i(15, 3))
		var expansions := int(probe.counters.get("navigation.expanded_nodes", 0))
		var hits := int(probe.counters.get("navigation.cell_cache_hits", 0))
		check(finder.find_cell_path(Vector2i(2, 3), Vector2i(15, 3)) == raw, "cell corridor is reusable")
		check(int(probe.counters.get("navigation.expanded_nodes", 0)) == expansions and int(probe.counters.get("navigation.cell_cache_hits", 0)) == hits + 1, "repeated formation corridor runs no search")
		var endpoint_grid = Grid.new(Vector2i(40, 40))
		endpoint_grid.configure_terrain(func(cell): return "grass" if cell.y == 20 and cell.x <= 10 else "water")
		var endpoint_finder = Finder.new(endpoint_grid)
		endpoint_finder.set_native_enabled(native)
		check(not endpoint_finder.find_path(Vector2(2.5, 20.5), Vector2(20.5, 20.5)).is_empty(), "blocked endpoint resolves to an accessible nearby cell")
		endpoint_grid.set_terrain(Vector2i(20, 15), "grass")
		check(endpoint_finder.find_path(Vector2(2.5, 20.5), Vector2(20.5, 20.5)).is_empty(), "a new nearer endpoint outside old route bounds invalidates endpoint correction")
		for index in range(Finder.MAX_ROUTE_CACHE_ENTRIES + 20):
			finder.find_path(Vector2(2.01 + float(index) * 0.0002, 8.5), Vector2(8.5, 8.5))
		check(finder.cache.size() == Finder.MAX_ROUTE_CACHE_ENTRIES, "bounded eviction does not erase all route history")
		check(finder.geometry_metadata["world"].size() == finder.cache.size(), "geometry metadata evicts with routes")
	for failure in failures: push_error(failure)
	print("Navigation cache coherence: %d failures" % failures.size())
	quit(0 if failures.is_empty() else 1)
func check(value: bool, message: String) -> void:
	if not value: failures.append(message)
